# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tocr.proto\";\n\nOCRRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\x0c\"\x18\n\x0b\x43oordinates\x12\t\n\x01i\x18\x01 \x03(\x03\"N\n\x07OCRText\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12!\n\x0b\x63oordinates\x18\x03 \x03(\x0b\x32\x0c.Coordinates\"E\n\x0bOCRResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x16\n\x04text\x18\x06 \x03(\x0b\x32\x08.OCRText20\n\nOCRService\x12\"\n\x03OCR\x12\x0b.OCRRequest\x1a\x0c.OCRResponse\"\x00\x62\x06proto3')



_OCRREQUEST = DESCRIPTOR.message_types_by_name['OCRRequest']
_COORDINATES = DESCRIPTOR.message_types_by_name['Coordinates']
_OCRTEXT = DESCRIPTOR.message_types_by_name['OCRText']
_OCRRESPONSE = DESCRIPTOR.message_types_by_name['OCRResponse']
OCRRequest = _reflection.GeneratedProtocolMessageType('OCRRequest', (_message.Message,), {
  'DESCRIPTOR' : _OCRREQUEST,
  '__module__' : 'ocr_pb2'
  # @@protoc_insertion_point(class_scope:OCRRequest)
  })
_sym_db.RegisterMessage(OCRRequest)

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATES,
  '__module__' : 'ocr_pb2'
  # @@protoc_insertion_point(class_scope:Coordinates)
  })
_sym_db.RegisterMessage(Coordinates)

OCRText = _reflection.GeneratedProtocolMessageType('OCRText', (_message.Message,), {
  'DESCRIPTOR' : _OCRTEXT,
  '__module__' : 'ocr_pb2'
  # @@protoc_insertion_point(class_scope:OCRText)
  })
_sym_db.RegisterMessage(OCRText)

OCRResponse = _reflection.GeneratedProtocolMessageType('OCRResponse', (_message.Message,), {
  'DESCRIPTOR' : _OCRRESPONSE,
  '__module__' : 'ocr_pb2'
  # @@protoc_insertion_point(class_scope:OCRResponse)
  })
_sym_db.RegisterMessage(OCRResponse)

_OCRSERVICE = DESCRIPTOR.services_by_name['OCRService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OCRREQUEST._serialized_start=13
  _OCRREQUEST._serialized_end=72
  _COORDINATES._serialized_start=74
  _COORDINATES._serialized_end=98
  _OCRTEXT._serialized_start=100
  _OCRTEXT._serialized_end=178
  _OCRRESPONSE._serialized_start=180
  _OCRRESPONSE._serialized_end=249
  _OCRSERVICE._serialized_start=251
  _OCRSERVICE._serialized_end=299
# @@protoc_insertion_point(module_scope)
