# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import ocr_pb2 as ocr__pb2


class OCRServiceStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OCR = channel.unary_unary(
                '/OCRService/OCR',
                request_serializer=ocr__pb2.OCRRequest.SerializeToString,
                response_deserializer=ocr__pb2.OCRResponse.FromString,
                )


class OCRServiceServicer(object):
    """The service definition.
    """

    def OCR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OCRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OCR': grpc.unary_unary_rpc_method_handler(
                    servicer.OCR,
                    request_deserializer=ocr__pb2.OCRRequest.FromString,
                    response_serializer=ocr__pb2.OCRResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OCRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OCRService(object):
    """The service definition.
    """

    @staticmethod
    def OCR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OCRService/OCR',
            ocr__pb2.OCRRequest.SerializeToString,
            ocr__pb2.OCRResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
